api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: false
        security: "is_granted('ROLE_USER')"
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
